# Generated by Django 5.2.17 on 2026-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=5000)),
                ('ip_hash', models.CharField(blank=True, help_text='Salted hash, never a raw IP.', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('spam', 'Spam')], default='new', max_length=10)),
                ('spam_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
