# Generated by Django 5.2.17 on 2026-09-30 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('stackoverflow', 'Stack Overflow'), ('devto', 'dev.to'), ('hashnode', 'Hashnode'), ('pypi', 'PyPI'), ('cratesio', 'crates.io'), ('x', 'X'), ('youtube', 'YouTube'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('rel_me', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='Muhammad Umer', max_length=200)),
                ('alternate_names', models.JSONField(blank=True, default=list)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('bio_short', models.CharField(blank=True, max_length=300)),
                ('bio_md', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('resume_pdf', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('available_for_work', models.BooleanField(default=False)),
                ('public_email_visible', models.BooleanField(default=False)),
                ('location_display', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='portfolio_profile_singleton')],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.skillgroup')),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'name'), name='unique_skill_per_group')],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('project', 'Project'), ('milestone', 'Milestone'), ('learning', 'Learning')], max_length=20)),
                ('status', models.CharField(blank=True, choices=[('shipped', 'Shipped'), ('building', 'Building'), ('archived', 'Archived')], max_length=20)),
                ('date', models.DateField(help_text='Stored at month precision (first of the month).')),
                ('summary', models.CharField(max_length=600)),
                ('body_md', models.TextField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('live_url', models.URLField(blank=True)),
                ('repo_url', models.URLField(blank=True)),
                ('writeup_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='entries/')),
                ('is_published', models.BooleanField(default=False)),
                ('is_sample', models.BooleanField(default=False, help_text='Sample/placeholder content. Excluded from sitemaps, JSON-LD and search.')),
                ('seo_title', models.CharField(blank=True, max_length=60)),
                ('seo_description', models.CharField(blank=True, max_length=160)),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='portfolio.tag')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['-date', 'title'],
                'indexes': [models.Index(fields=['kind', 'is_published'], name='portfolio_e_kind_ab293e_idx')],
            },
        ),
    ]
